# Generated by Django 4.2.1 on 2025-08-24 19:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "fixed_stake_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Giá trị cược cố định (nếu có)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "stake_type",
                    models.CharField(
                        choices=[("FIXED", "Cược cố định"), ("FREE", "Cược tự do")],
                        default="FREE",
                        max_length=20,
                    ),
                ),
                (
                    "current_odds",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                (
                    "min_stake",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=10
                    ),
                ),
                (
                    "max_stake",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_purchases",
                    models.IntegerField(default=0, help_text="Tổng số lượt mua"),
                ),
                (
                    "popularity_score",
                    models.IntegerField(
                        default=0, help_text="Điểm phổ biến để sắp xếp"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProductPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("stake_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "odds_at_purchase",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ xử lý"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("SETTLED", "Đã thanh toán"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "featured_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_purchases",
                        to="carousel.featuredevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="featuredevent",
            index=models.Index(
                fields=["is_active", "order"], name="carousel_fe_is_acti_f59ab7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featuredevent",
            index=models.Index(
                fields=["popularity_score"], name="carousel_fe_popular_f11c44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featuredevent",
            index=models.Index(
                fields=["created_at"], name="carousel_fe_created_157eb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userproductpurchase",
            index=models.Index(
                fields=["user", "status"], name="carousel_us_user_id_4c18b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userproductpurchase",
            index=models.Index(
                fields=["featured_event", "status"],
                name="carousel_us_feature_86a1fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userproductpurchase",
            index=models.Index(
                fields=["purchased_at"], name="carousel_us_purchas_3e50d4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userproductpurchase",
            unique_together={("user", "featured_event")},
        ),
    ]
